### ISSUE TITLE
Modify our current search engine

### ISSUE THREAD

**Issue by danbugs** [danbugs/smithereens#108]
**Describe the solution you'd like**
This involves two things:
(1) I'd like exact matches of a tag searched to display at the top (e.g., when searching "tenant", we should get the result exactly matching that on the first page rather than on the third one behind tons of "lieutenants").
(2) Allow to search by ID/user slug (related to #106)

**Additional context**
n/a

**Comment by ghost** [comment]
Since start.gg allows gamertags containing nothing but numbers, I will try to have them listed in this order:

ID exact match (if all numbers, otherwise skip),
slug exact match,
gamertag exact match,
gamertag similar matches.

This should cover all cases without having separate boxes/filters. Let me know if I'm missing something

**Comment by danbugs** [comment]
Yeah, that sounds good to me - Another option to consider is adding text filters to the search, like specifying smt like an "id:" prefix when searching by ID (e.g., "id:123456"), but I'll leave that up to you 👍

**Comment by ghost** [comment]
> Yeah, that sounds good to me - Another option to consider is adding text filters to the search, like specifying smt like an "id:" prefix when searching by ID (e.g., "id:123456"), but I'll leave that up to you 👍

I didn't want to do this because I don't know exactly what characters start.gg allows/doesn't.
For example this account has an underscore and semicolon
https://www.start.gg/user/aed08833
If colons are allowed and someone was to name themselves "tag:test" and tried searching for it, they'd get the account named test instead of their own

**Comment by danbugs** [comment]
Yep - that's a fair concern. I like the approach you mentioned prior 👍
